dist: trusty

language: node_js

node_js:
  - "10"

branches:
  only:
    - master

install:
  - echo 'Install step'

script:
  - echo 'Script step'
  - mkdir dist
  - mkdir dist/images
  - cp favicon.ico index.html normalize.css dist/
  - cp images/tailwind-logo.png dist/images/

deploy:
  - provider: surge
    project: ./dist/
    domain: tailwindcss-trial.surge.sh
    on: master
