dist: trusty

language: node_js

node_js:
  - "10"

branches:
  only:
    - master

install:
  - echo 'Install step'

script:
  - echo 'Script step'
  - mkdir dist && mkdir dist/images && mkdir dist/css
  - cp src/main/webapp/css/*.css  dist/css/
  - cp src/main/webapp/images/*.*  dist/images/
  - cp src/main/webapp/*.* dist/

deploy:
  - provider: surge
    project: ./dist/
    domain: tailwindcss-trial.surge.sh
    on: master
